### ISSUE TITLE
Failed to process committed block (285189922:7BAFC2A2AC7D2E1EA504F450BB0D247DACABD9C904F203B4211D7655D4187662): Wrong Block.Header.AppHash. 

### ISSUE THREAD

**Issue by luoxiandong** [bnb-chain/node#898] opened 2022-12-20 00:26 UTC
My bnb node version:v0.10.3, run and the following error occurred:
clean node data an  runs again, the same error will still occur.
```
s=0 numOfProposals=0 numOfSideProposals=0 numOfStakeUpdates=0 numOfAccounts=1
I[2022-12-20|00:08:15.343] Executed block                               module=state height=285189919 validTxs=1 invalidTxs=0
I[2022-12-20|00:08:15.413] Committed state                              module=state height=285189919 txs=1 appHash=6F165432C32A0EA570D9CE870B05EC551D5AD269F5F8B18F1D90A51B5391A1C0
I[2022-12-20|00:08:15.426] symbols to match                             module=dexkeeper symbols=[]
I[2022-12-20|00:08:15.426] No order comes in for the block              module=dexkeeper
I[2022-12-20|00:08:15.426] Sync params proposals.                       module=paramHub
I[2022-12-20|00:08:15.436] start to collect publish information         module=pub height=285189920
I[2022-12-20|00:08:15.436] start to publish                             module=pub height=285189920 blockTime=1671459274548073755 numOfTrades=0 numOfOrders=0 numOfProposals=0 numOfSideProposals=0 numOfStakeUpdates=0 numOfAccounts=3
I[2022-12-20|00:08:15.436] Executed block                               module=state height=285189920 validTxs=3 invalidTxs=0
I[2022-12-20|00:08:15.497] Committed state                              module=state height=285189920 txs=3 appHash=8E14527BAE13FB640135D6F29800E189ED93B8D8AE07ED5EB8A02EC8CECA2FFC
E[2022-12-20|00:08:15.509] process package failed, channel=16, sequence=7, error=ERROR:
Codespace: 11
Code: 1010
Message: "channel 16 not registered"
 module=oracle 
I[2022-12-20|00:08:15.510] symbols to match                             module=dexkeeper symbols=[]
I[2022-12-20|00:08:15.510] No order comes in for the block              module=dexkeeper
I[2022-12-20|00:08:15.510] Sync params proposals.                       module=paramHub
I[2022-12-20|00:08:15.519] start to collect publish information         module=pub height=285189921
I[2022-12-20|00:08:15.520] start to publish                             module=pub height=285189921 blockTime=1671459274988498177 numOfTrades=0 numOfOrders=0 numOfProposals=0 numOfSideProposals=0 numOfStakeUpdates=0 numOfAccounts=1
I[2022-12-20|00:08:15.520] Executed block                               module=state height=285189921 validTxs=1 invalidTxs=1
I[2022-12-20|00:08:15.581] Committed state                              module=state height=285189921 txs=2 appHash=5D4081E67851B71D01AFCE249EE311AAF4137A08FFA37E6D4506C4FA3DCA416F
panic: Failed to process committed block (285189922:7BAFC2A2AC7D2E1EA504F450BB0D247DACABD9C904F203B4211D7655D4187662): Wrong Block.Header.AppHash.  Expected 5D4081E67851B71D01AFCE249EE311AAF4137A08FFA37E6D4506C4FA3DCA416F, got A8CE31F9A383005172D3C5073C1C62576D284EFEE2E538C9D49EEAA5F8D7D545

goroutine 10264 [running]:
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc000dea1a0)
        github.com/tendermint/tendermint@v0.32.3/blockchain/v0/reactor.go:404 +0x1aa5
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).SwitchToBlockchain
        github.com/tendermint/tendermint@v0.32.3/blockchain/v0/reactor.go:154 +0x305
```

app.toml
```# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

[base]
# Interval blocks of breathe block, if breatheBlockInterval is 0, breathe block will be created every day.
breatheBlockInterval = 0
# Size of account cache
accountCacheSize = 30000
# Size of signature cache
signatureCacheSize = 30000
# Running mode when start up, 0: Normal, 1: TransferOnly, 2: RecoverOnly
startMode = 0
# Concurrency of OrderKeeper, should be power of 2
orderKeeperConcurrency = 2
# Days count back for breathe block
breatheBlockDaysCountBack = 7

[upgrade]
# Block height of BEP6 upgrade
BEP6Height = 20300000
# Block height of BEP9 upgrade
BEP9Height = 20300000
# Block height of BEP10 upgrade
BEP10Height = 20300000
# Block height of BEP19 upgrade
BEP19Height = 20300000
# Block height of BEP12 upgrade
BEP12Height = 25120000
# Block height of BEP3 upgrade
BEP3Height = 41277000
# Block height of FixSignBytesOverflow upgrade
FixSignBytesOverflowHeight = 51467800
# Block height of LotSizeOptimization upgrade
LotSizeUpgradeHeight = 51467800
# Block height of changing listing rule upgrade
ListingRuleUpgradeHeight = 51467800
# Block height of FixZeroBalanceHeight upgrade
FixZeroBalanceHeight = 51467800
# Block height of BEP8 upgrade
BEP8Height = 99550000
# Block height of BEP67 upgrade
BEP67Height = 99550000
# Block height of BEP70 upgrade
BEP70Height = 99550000
# Block height of smart chain upgrade
LaunchBscUpgradeHeight = 109999000
# Block height of BEP82Height upgrade
BEP82Height = 146060000
# Block height of BEP84Height upgrade
BEP84Height = 146060000
# Block height of BEP87Height upgrade
BEP87Height = 146060000
# Block height of FixFailAckPackage upgrade
FixFailAckPackageHeight = 146060000
# Block height of Enable Account Scripts For CrossChain Transfer upgrade
EnableAccountScriptsForCrossChainTransferHeight = 146060000
#Block height of BEP128 upgrade
BEP128Height = 234560000
#Block height of BEP151 upgrade
BEP151Height = 264000000
#Block height of BEP153 upgrade
BEP153Height = 284376000
#Block height of BEP173 upgrade
BEP173Height = 284376000

[addr]
# Bech32PrefixAccAddr defines the Bech32 prefix of an account's address
bech32PrefixAccAddr = "bnb"
# Bech32PrefixAccPub defines the Bech32 prefix of an account's public key
bech32PrefixAccPub = "bnbp"
# Bech32PrefixValAddr defines the Bech32 prefix of a validator's operator address
bech32PrefixValAddr = "bva"
# Bech32PrefixValPub defines the Bech32 prefix of a validator's operator public key
bech32PrefixValPub = "bvap"
# Bech32PrefixConsAddr defines the Bech32 prefix of a consensus node address
bech32PrefixConsAddr = "bca"
# Bech32PrefixConsPub defines the Bech32 prefix of a consensus node public key
bech32PrefixConsPub = "bcap"

##### publication related configurations #####
[publication]
# configurations ends with Kafka can be a semi-colon separated host-port list
# Whether we want publish market data (this includes trades and order)
publishOrderUpdates = true
orderUpdatesTopic = "orders"
orderUpdatesKafka = "127.0.0.1:9092"

# Whether we want publish account balance to notify browser db indexer persist latest account balance change
publishAccountBalance = true
accountBalanceTopic = "accounts"
accountBalanceKafka = "127.0.0.1:9092"

# Whether we want publish order book changes
publishOrderBook = true
orderBookTopic = "orders"
orderBookKafka = "127.0.0.1:9092"

# Whether we want publish block fee changes
publishBlockFee = true
blockFeeTopic = "accounts"
blockFeeKafka = "127.0.0.1:9092"

# Whether we want publish transfers
publishTransfer = true
transferTopic = "transfers"
transferKafka = "127.0.0.1:9092"

# Whether we want publish distribution
publishDistributeReward = false
distributeRewardTopic = "distribution"
distributeRewardKafka = "127.0.0.1:9092"

# Whether we want publish staking
publishStaking = false
stakingTopic = "staking"
stakingKafka = "127.0.0.1:9092"

# Whether we want publish slashing
publishSlashing = false
slashingTopic = "slashing"
slashingKafka = "127.0.0.1:9092"

# Whether we want publish cross transfer
publishCrossTransfer = false
crossTransferTopic = "crossTransfer"
crossTransferKafka = "127.0.0.1:9092"

## Whether we want publish mirror events
publishMirror = false
mirrorTopic = "mirror"
mirrorKafka = "127.0.0.1:9092"

# Whether we want publish side proposals
publishSideProposal = false
sideProposalTopic = "sideProposal"
sideProposalKafka = "127.0.0.1:9092"

# Whether we want publish breatheBlock
publishBreatheBlock = false
breatheBlockTopic = "breatheBlock"
breatheBlockKafka = "127.0.0.1:9092"

# Global setting
publicationChannelSize = "10000"
publishKafka = false
publishLocal = true
# max size in megabytes of marketdata json file before rotate
localMaxSize = 1024
# max days of marketdata json files to keep before deleted
localMaxAge = 7

[log]

# Write logs to console instead of file
logToConsole = true

## The below parameters take effect only when logToConsole is false
# Log file root, if not set, use home path
logFileRoot = ""
# Log file path relative to log file root path
logFilePath = "bnc.log"
# Number of logs keep in memory before writing to file
logBuffSize = 10000

[cross_chain]
ibcChainId = 1
bscChainId = "bsc"
bscIbcChainId = 56

[dex]
# The suffixed symbol of BUSD
BUSDSymbol = "BUSD-BD1"
```

**Comment by guagualvcha** [comment] 2022-12-26 04:59
hi, @luoxiandong  thanks for reporting this, this is a critical bugs, we will fix it ASAP.

**Comment by guagualvcha** [comment] 2022-12-29 01:56
hi, @luoxiandong  the issue is fixed in the latest release, please check.

**Closed as completed by guagualvcha** 2022-12-29 01:56 UTC
